// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {PlasmicAuth} from "./plasmic/website_starter/PlasmicAuth";
import {useState} from "react";

import {createClient} from '@/utils/supabase/client'
import {useRouter} from "next/router";

function Auth_(props, ref) {
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const router = useRouter();
    const supabase = createClient();
    return (<PlasmicAuth root={{ref}} {...props}
                         emailInput={{
                             value: email,
                             onChange: (e) => setEmail(e.target.value)
                         }
                         }
                         passwordInput={{
                             value: password,
                             onChange: (e) => setPassword(e.target.value)
                         }}
                         submitButton={{
                             onClick: async () => {
                                 let loginfunc = null

                                 loginfunc = await supabase.auth.signInWithPassword({
                                     email: email,
                                     password: password
                                 })
                                 const {data} = loginfunc;
                                 console.log(data)
                                 const {error} = loginfunc
                                 if (error){ return console.log(error)}
                                 router.replace("/")

                             }
                         }}
    />);
}

const Auth = React.forwardRef(Auth_);

export default Auth;
